### ISSUE TITLE
documentation - docker helper

### ISSUE THREAD

**Issue by vinnie357** [f5devcentral/f5-big-iq-onboarding#2]
in step 7 and 8,

the docker helper maps the root as a volume, but the playbook files are in root and not root/playbooks so the run command fails to find the playbooks.

./ansible_helper ansible-playbook /ansible/**playbooks**/bigiq_onboard_pretasks_aws.yml
Execute the BIG-IQ onboarding playbooks.

./ansible_helper ansible-playbook /ansible/**playbooks**/bigiq_onboard.yml

**Comment by rjouhann** [comment]
thanks @vinnie357 corrected the README
