### ISSUE TITLE
ansible can't see the hosts inventory

### ISSUE THREAD

**Issue by vinnie357** [f5devcentral/f5-big-iq-onboarding#3]
Ansible in the container seems to ignore the ansible.cfg
says ./hosts is not found, but the file is available if you run:

.ansible_helper ansible-playbook cat /ansible/hosts

If I specify the inventory file it is successful: 

./ansible_helper ansible-playbook **-i /ansible/hosts** /ansible/bigiq_onboard.yml

**Comment by rjouhann** [comment]
fixed, thanks @vinnie357
