### ISSUE TITLE
name for container in helper

### ISSUE THREAD

**Issue by vinnie357** [f5devcentral/f5-big-iq-onboarding#5]
step 5:
sudo docker build . -t **f5-big-iq-onboarding**

helper file:
`
sudo docker run --rm -it \
  -v ~/.ssh:/root/.ssh \
  -v $(pwd):/ansible \
  f5-bigiq-onboarding "$@"
`

lets update the helper to match the docker image.
f5-bigiq-onboarding != f5-big-iq-onboarding

**Comment by rjouhann** [comment]
Thanks! done
